#!/bin/bash
#
# init.d script for EventLCD Server
#
#
### BEGIN INIT INFO
# Provides:     sshd
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:
# Short-Description:    EventLCD Server
### END INIT INFO

# Get function from functions library
. /etc/init.d/functions
# Start the service FOO
start() {
        initlog -c "echo -n Starting EventLCD server: "
        cd /path/to/website/dir
        ./run.py &
        ### Create the lock file ###
        echo "$1" > /var/lock/subsys/EventLCD
        success $"EventLCD server startup"
        echo
}
# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping FOO server: "
        killproc $(cat /var/lock/subsys/EventLCD)

        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/EventLCD
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        if [ -e "/var/lock/subsys/EventLCD" ]
        then
            echo "EventLCD is Running!"
        else
            echo "EventLCD is Not Running!"
        fi
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
